name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          submodules: 'true'

      - name: Build
        uses: jerryjvl/jekyll-build-action@v1

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: main
          folder: _site
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          repository-name: pyocd/pyocd.github.io
          git-config-name: pyocd-bot
          git-config-email: pyocd-bot-noreply@pyocd.io
          clean: true
          clean-exclude: |
            .nojekyll
            CNAME
